apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spirrello/kustomize_base.git
    targetRevision: HEAD
    path: kustomize/backend-api/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
