apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/spirrello/kustomize_base.git/kustomize/base
  - https://github.com/spirrello/kustomize_base.git/kustomize/hpa_cpu
  - flux_app.yaml
namespace: backend-api-dev
images:
  - name: app
    newName: nginx
    newTag: 1.15.0
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: backend-api
patches:
  - patch: |-
      - op: add
        path: "/metadata/name"
        value: "backend-api"
    target:
      name: frontend
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/name"
        value: "backend-api"
    target:
      kind: Deployment
      name: frontend
  - path: hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
  # - patch: |-
  #     - op: replace
  #       path: "/spec/targetNamespace"
  #       value: "backend-api-dev"
  #   target:
  #     kind: Kustomization
  #     name: backend-api
