---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: backend-api
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/spirrello/kustomize_base.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend-api
  namespace: default
spec:
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: backend-api
  path: "."
  prune: true
  timeout: 1m
