apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git@github.com:spirrello/kustomize_base.git/base
namespace: backend-api-dev
labels:
  - pairs:
      app: backend-api
    includeSelectors: true
    includeTemplates: true
patches:
  - path: hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
  - patch: |-
      - op: replace
        path: "/metadata/name"
        value: "backend-api"
    target:
      name: frontend
