apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: backend-api
  name: backend-api-dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-api
  name: backend-api
  namespace: backend-api-dev
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: backend-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-api
  name: backend-api
  namespace: backend-api-dev
spec:
  selector:
    matchLabels:
      app: backend-api
  spec:
    containers:
    - image: foo/bar:latest
      name: app
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  template:
    metadata:
      labels:
        app: backend-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: backend-api
  name: backend-api
  namespace: backend-api-dev
spec:
  apiVersion: apps/v1
  kind: Deployment
  maxReplicas: 10
  metrics:
  - type: Resource
  minReplicas: 1
  name: frontend
  resource:
    name: cpu
    target:
      averageUtilization: 70
      type: Utilization
