apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: app
          image: foo/bar:latest
          resources:
            limits:
              cpu: ".5"
              memory: "128Mi"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
