apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
  spec:
    containers:
      - name: app
        image: foo/bar:latest
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
